name: CI/CD

on:
  push:
    branches: [ master,feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: UnitTests+Integration tests
      run: dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/DevopsPractice/*.cs" /p:Threshold=90

  deployDev:
    
    runs-on: ubuntu-latest
    
    environment: Development
    
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Heroku

      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: ${{ secrets.APP_NAME }}
        
  testApiDev:
    
    runs-on: ubuntu-latest
    
    environment: Development
    
    needs: deployDev
    
    steps:
    - uses: actions/checkout@v2
    
    # Install Node.js environment
    - name: set up node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'

    # Install newman
    - name: Install newman
      run: | 
       npm install -g newman
      
    # Run POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       newman run ./DevopsPractice.Tests.Behavior/Postman/TestCalculadora.postman_collection.json -e ./DevopsPractice.Tests.Behavior/Postman/Environments/Development.postman_environment.json --iteration-data ./DevopsPractice.Tests.Behavior/Postman/calc-test-data.csv 
    
  deployStaging:
    
    runs-on: ubuntu-latest
    
    environment: Staging
    
    needs: testApiDev

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Heroku

      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: ${{ secrets.APP_NAME }}
        
  UAT:
    
    runs-on: ubuntu-latest
    
    environment: Staging
    
    needs: deployStaging
    
    steps:
    - uses: actions/checkout@v2
    
    # Install Node.js environment
    - name: set up node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'

    # Install newman
    - name: Install newman
      run: | 
       npm install -g newman
      
    # Run POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       newman run ./DevopsPractice.Tests.Behavior/Postman/TestCalculadora.postman_collection.json -e ./DevopsPractice.Tests.Behavior/Postman/Environments/Staging.postman_environment.json --iteration-data ./DevopsPractice.Tests.Behavior/Postman/calc-test-data.csv 
