name: CI/CD

on:
  push:
    branches: [ master,feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: UnitTests+Integration tests
      run: dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/DevopsPractice/*.cs" /p:Threshold=90

  deployDev:
    
    runs-on: ubuntu-latest
    
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Heroku

      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: ${{ secrets.APP_NAME }}
        
  testApiDev:
    
    runs-on: ubuntu-latest
    
    needs: deployDev
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Newman Action
      # You may pin to the exact commit or the version.
      # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
      uses: matt-ball/newman-action@v0.2.4
      with:
        # Postman API key
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        # Collection to use
        collection: DevopsPractice.Tests.Behavior\Postman\TestCalculadora.postman_collection.json
        # Environment to use
        environment: DevopsPractice.Tests.Behavior\Postman\Environments\Development.postman_environment.json
        # Path to CSV or JSON data file
        iterationData: DevopsPractice.Tests.Behavior\Postman\calc-test-data.csv

