name: CI/CD

on:
  push:
    branches: [ master,feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: UnitTests+Integration tests
      run: dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/DevopsPractice/*.cs" /p:Threshold=90

  deployDev:
    
    runs-on: ubuntu-latest
    
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Heroku

      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        # Email Linked to your Heroku Account
        email: ${{ secrets.HEROKU_EMAIL }}
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: ${{ secrets.APP_NAME }}
        
  testApiDev:
    
    runs-on: ubuntu-latest
    
    needs: deployDev
    
    steps:
    - uses: actions/checkout@v2
    
    # Install Node.js environment
    - name: set up node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'

    # Install newman
    - name: Install newman
      run: | 
       npm install -g newman
       npm install -g newman-reporter-htmlextra\
       
    - name: Make Directory for results
      run: mkdir -p testResults
      
    # Run POSTMAN collection and output the file as html
    - name: Run POSTMAN collection
      run: |
       newman run ./DevopsPractice.Tests.Behavior/Postman/TestCalculadora.postman_collection.json -e ./DevopsPractice.Tests.Behavior/Postman/Environments/Development.postman_environment.json --iteration-data /test/calc-test-data.csv -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
    
    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
