name: CI

on:
  push:
    branches: [ master,feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: UnitTests+Integration tests
      run: dotnet test --no-build /p:CollectCoverage=true /p:ExcludeByFile="**/DevopsPractice/*.cs" /p:Threshold=90
